# Generated by Django 3.2.9 on 2021-11-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateField(default=datetime.date(2021, 11, 28))),
                ('end', models.DateField(default=datetime.date(2021, 11, 28))),
                ('place', models.CharField(max_length=100)),
                ('amount_of_fund', models.FloatField(default=0)),
                ('require_volunteers_number', models.IntegerField(default=0)),
                ('now_volunteers_number', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('info_program', models.JSONField(default={'program_id': []}, help_text='the information of program of the event')),
                ('info_volunteer', models.JSONField(default={'volunteer_information': []}, help_text='the information of volunteers join the event')),
                ('info_donor', models.JSONField(default={'donor_information': []}, help_text='the information of donors')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateField(default=datetime.date(2021, 11, 28))),
                ('end', models.DateField(default=datetime.date(2021, 11, 28))),
                ('status', models.IntegerField(default=0)),
                ('amount_of_fund', models.FloatField(default=0)),
                ('info_volunteer', models.JSONField(default={'volunteer_information': []}, help_text='the information of volunteers join the event')),
                ('info_donor', models.JSONField(default={'donor_information': []}, help_text='the information of donors')),
            ],
        ),
    ]
