# Generated by Django 3.2.9 on 2021-11-29 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 24, 40, 571415)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 24, 40, 571415)),
        ),
        migrations.AlterField(
            model_name='program',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 11, 29, 20, 24, 40, 571415)),
        ),
        migrations.AlterField(
            model_name='program',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 11, 29, 20, 24, 40, 571415)),
        ),
    ]
