# Generated by Django 3.2.9 on 2021-11-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211129_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 244728)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 243727)),
        ),
        migrations.AlterField(
            model_name='program',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 244728)),
        ),
        migrations.AlterField(
            model_name='program',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 244728)),
        ),
    ]
