# Generated by Django 3.2.9 on 2021-11-29 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20211129_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='info_program',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end',
        ),
        migrations.RemoveField(
            model_name='program',
            name='info_volunteer',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 23, 58, 17, 805537)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 23, 58, 17, 805537)),
        ),
        migrations.AlterField(
            model_name='program',
            name='event',
            field=models.JSONField(default={'event_id': []}, help_text='the information of event of the program'),
        ),
    ]
