# Generated by Django 3.2.9 on 2021-11-30 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211129_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(default='1', max_length=100)),
                ('amount_of_fund', models.FloatField(default=0)),
                ('info_donor', models.JSONField(default={'donor_information': []}, help_text='the information of donors')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 15, 57, 22, 48486)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 15, 57, 22, 48486)),
        ),
    ]
