# Generated by Django 3.2.9 on 2021-11-28 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='end',
            field=models.TimeField(default=datetime.datetime(2021, 11, 28, 14, 54, 27, 480372)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='start',
            field=models.TimeField(default=datetime.datetime(2021, 11, 28, 14, 54, 27, 480372)),
        ),
    ]
