# Generated by Django 3.2.9 on 2021-11-28 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211128_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='end',
            field=models.TimeField(default=datetime.datetime(2021, 11, 28, 15, 7, 43, 689093)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='start',
            field=models.TimeField(default=datetime.datetime(2021, 11, 28, 15, 7, 43, 689093)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
