# Generated by Django 3.2.9 on 2021-11-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211128_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproflie',
            name='donor_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userproflie',
            name='donor_information',
            field=models.JSONField(default={'donor_information': []}),
        ),
        migrations.AddField(
            model_name='userproflie',
            name='event_doing',
            field=models.JSONField(default={'event': []}),
        ),
        migrations.AddField(
            model_name='userproflie',
            name='event_joined',
            field=models.JSONField(default={'event': []}),
        ),
        migrations.AddField(
            model_name='userproflie',
            name='working_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 20, 15, 15, 370335)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 20, 15, 15, 370335)),
        ),
    ]
