# Generated by Django 3.2.9 on 2021-11-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211129_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 236727)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 20, 25, 37, 236727)),
        ),
    ]
